export const CONFIG = {
  GITHUB_USERNAME: 'fawwazhakeeeem19',
  name: 'Fawwaz Hakim',
  title: 'Full-Stack Developer & Cybersecurity Enthusiast',
  tagline: 'Building the future, one commit at a time.',
  bio: 'Seorang Pelajar SMA berkeinginan Menjadi Fullstack developer & cyber enthusiast yang mengubah ide menjadi pengalaman digital yang aman.',
  location: 'Tuban, East Java, Indonesia 🇮🇩',
  email: 'inaamfawwazhakim01@gmail.com',

  social: {
    github: 'https://github.com/fawwazhakeeeem19',
    instagram: 'https://www.instagram.com/fawwaz.hakeeem',
    discord: 'https://discord.com/users/757035744090128407',
  },

  skills: [
    { name: 'React', level: 92, category: 'Frontend', color: '#61dafb' },
    { name: 'TypeScript', level: 88, category: 'Language', color: '#3178c6' },
    { name: 'Node.js', level: 85, category: 'Backend', color: '#68a063' },
    { name: 'Python', level: 80, category: 'Language', color: '#f7cc41' },
    { name: 'Next.js', level: 87, category: 'Frontend', color: '#ffffff' },
    { name: 'Tailwind', level: 83, category: 'Frontend', color: '#38bdf8' },
    { name: 'Penetration Testing', level: 82, category: 'Cybersecurity', color: '#ff3b30' },
    { name: 'Network Security', level: 78, category: 'Cybersecurity', color: '#0a84ff' },
    { name: 'Wireshark', level: 76, category: 'Tools', color: '#32ade6' },
    { name: 'Nmap', level: 79, category: 'Tools', color: '#30d158' },
    { name: 'Burp Suite', level: 74, category: 'Web Security', color: '#ff9f0a' },
    { name: 'OSINT', level: 81, category: 'Intelligence', color: '#bf5af2' },
    { name: 'Web Exploitation', level: 73, category: 'Web Security', color: '#ff375f' },
    { name: 'SQL Injection', level: 70, category: 'Web Security', color: '#64d2ff' },
    { name: 'Python Automation', level: 84, category: 'Programming', color: '#3776ab' },
    { name: 'Cryptography', level: 68, category: 'Security', color: '#8e8e93' },
  ],

  timeline: [
    {
      year: '2026',
      title: 'Full-Stack Developer & Cybersecurity Enthusiast',
      company: 'SMA PLUS AR-Rahmat',
      description: 'Menjadi pekerja paruh waktu dan menjadi salah satu dari bagian perusahaan di bidang IT dan investasi.',
      tags: ['Network Security', 'Cryptography', 'Golang'],
      type: 'work' as const,
    },
    {
      year: '2026',
      title: 'Front-End Developer',
      company: 'ARMASO',
      description: 'Membangun sebuah website bersama rekan-rekan untuk website perlombaan.',
      tags: ['React', 'Tailwind', 'Python', 'Next.js', 'BurpSuite'],
      type: 'work' as const,
    },
    {
      year: '2025',
      title: 'Memulai Sekolah Menengah Atas',
      company: 'SMA PLUS AR-Rahmat',
      description: 'Memasuki Sekolah Menengah Atas dan mengikuti beberapa bootcamp fullstack developer dan cybersecurity.',
      tags: ['Bootcamp', 'Fullstack', 'Cybersecurity'],
      type: 'education' as const,
    },
    {
      year: '2024',
      title: 'Fokus Pemrograman & Cybersecurity',
      company: 'SMP PLUS AR-RAHMAT',
      description: 'Memutuskan untuk belajar dan berlatih bahasa pemrograman dan ethical hacking secara serius.',
      tags: ['Python', 'Ethical Hacking', 'Linux'],
      type: 'achievement' as const,
    },
    {
      year: '2024',
      title: 'Lulus Sekolah Menengah Pertama',
      company: 'SMP PLUS AR-RAHMAT',
      description: 'Lulus Sekolah Menengah Pertama di SMP PLUS AR-Rahmat dengan semangat melanjutkan ke jenjang berikutnya.',
      tags: ['Graduation', 'Achievement'],
      type: 'education' as const,
    },
  ],

  featuredProjects: [],

  seo: {
    title: 'Fawwaz Hakim — Full-Stack Developer & Cybersecurity Enthusiast',
    description: 'Seorang Pelajar SMA yang menjadi Fullstack Developer & Cyber Enthusiast. Building the future, one commit at a time.',
    keywords: 'developer, portfolio, react, typescript, fullstack, cybersecurity, ethical hacking',
    ogImage: '/og-image.png',
  },
}

export const LANGUAGE_COLORS: Record<string, string> = {
  JavaScript: '#f1e05a',
  TypeScript: '#3178c6',
  Python: '#3572A5',
  Rust: '#dea584',
  Go: '#00ADD8',
  Java: '#b07219',
  'C++': '#f34b7d',
  C: '#555555',
  Ruby: '#701516',
  PHP: '#4F5D95',
  Swift: '#F05138',
  Kotlin: '#A97BFF',
  Dart: '#00B4AB',
  CSS: '#563d7c',
  HTML: '#e34c26',
  Shell: '#89e051',
  Vue: '#42b883',
  SCSS: '#c6538c',
}
